---
abstract: 'Perl interface to MXNet machine learning library'
author:
  - 'Sergey Kolychev <sergeykolychev.github@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-MXNet
requires:
  AI::MXNetCAPI: 0.01
  AI::NNVMCAPI: 0.01
  Function::Parameters: 1.0705
  Mouse: v2.1.0
  PDL: 2.007
  perl: v5.14.0
version: 0.01
